swagger: '2.0'
info:
  title: SUPERSEDE ReleasePlanner. Wrapper of Valentin's Implementation
  version: 2.0.0
host: localhost
schemes:
  - http
basePath: /api/v1
produces:
  - application/json
paths:
  /replan:
    post:
      summary: Generates a Planning Solution for a given Next Release Problem
      operationId: replan
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/NextReleaseProblem'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/PlanningSolution'
        '400':
          description: Bad Request
        '422':
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Error'
definitions:
  Skill:
    type: object
    properties:
      name:
        type: string
  Priority:
    type: object
    properties:
      level:
        type: integer
      score:
        type: integer
  Feature:
    type: object
    properties:
      name:
        type: string
      duration:
        type: number
        format: double
      priority:
        $ref: '#/definitions/Priority'
      required_skills:
        type: array
        items:
          $ref: '#/definitions/Skill'
      depends_on:
        type: array
        description: array of features
        items:
          $ref: '#/definitions/Feature'
  Resource:
    type: object
    properties:
      name:
        type: string
      availability:
        type: number
        format: double
      skills:
        type: array
        items:
          $ref: '#/definitions/Skill'
  AlgorithmParameters:
    type: object
    properties:
      algorithmType:
        type: string
        enum:
          - NSGA-II
          - MOCell
          - SPEA2
          - PESA2
          - SMSEMOA
      crossoverProbability:
        type: number
        format: double
      rateOfNotRandomSolution:
        type: number
        format: double
      numberOfIterations:
        type: integer
      populationSize:
        type: integer
  NextReleaseProblem:
    required: 
      - "features"
      - "resources"
      - "algorithmParameters"
      - "evaluationParameters"
    properties: 
      features: 
        type: "array"
        items: 
          type: "object"
          properties: 
            name: 
              type: "string"
            priority: 
              required: 
                - "level"
                - "score"
              properties: 
                level: 
                  type: "number"
                score: 
                  type: "number"
              type: "object"
            duration: 
              type: "number"
            required_skills: 
              type: "array"
              items: 
                type: "object"
                properties: 
                  name: 
                    type: "string"
            depends_on: 
              type: "array"
              items: 
                type: "string"
      resources: 
        type: "array"
        items: 
          type: "object"
          properties: 
            name: 
              type: "string"
            skills: 
              type: "array"
              items: 
                type: "object"
                properties: 
                  name: 
                    type: "string"
            calendar: 
              type: "array"
              items: 
                type: "object"
                properties: 
                  id: 
                    type: "number"
                  week: 
                    type: "number"
                  dayOfWeek: 
                    type: "number"
                  beginHour: 
                    type: "number"
                  endHour: 
                    type: "number"
                  status: 
                    type: "string"
      algorithmParameters: 
        required: 
          - "algorithmType"
          - "crossoverProbability"
          - "rateOfNotRandomSolution"
          - "numberOfIterations"
          - "populationSize"
        properties: 
          algorithmType: 
            type: "string"
          crossoverProbability: 
            type: "number"
          rateOfNotRandomSolution: 
            type: "number"
          numberOfIterations: 
            type: "number"
          populationSize: 
            type: "number"
        type: "object"
      evaluationParameters: 
        required: 
          - "objectives_list"
        properties: 
          objectives_list: 
            type: "array"
            items: 
              type: "object"
              properties: 
                0: 
                  type: "number"
                1: 
                  type: "number"
                2: 
                  type: "number"
                3: 
                  type: "number"
                4: 
                  type: "number"
        type: "object"
      replanTime: 
        required: 
          - "id"
          - "week"
          - "dayOfWeek"
          - "beginHour"
          - "endHour"
        properties: 
          id: 
            type: "number"
          week: 
            type: "number"
          dayOfWeek: 
            type: "number"
          beginHour: 
            type: "number"
          endHour: 
            type: "number"
        type: "object"
  PlannedFeature:
    type: object
    properties:
      beginHour:
        type: number
        format: double
      endHour:
        type: number
        format: double
      frozen:
        type: boolean
        default: false
        description: if true means it cannot be rescheduled
      resource:
        $ref: '#/definitions/Resource'
      feature:
        $ref: '#/definitions/Feature'
  PlanningSolution:
    required: 
      - "priorityQuality"
      - "performanceQuality"
      - "similarityQuality"
      - "globalQuality"
      - "employees"
    properties: 
      priorityQuality: 
        type: "number"
      performanceQuality: 
        type: "number"
      similarityQuality: 
        type: "number"
      globalQuality: 
        type: "number"
      employees: 
        type: "array"
        items: 
          type: "object"
          properties: 
            name: 
              type: "string"
            skills: 
              type: "array"
              items: 
                type: "object"
                properties: 
                  name: 
                    type: "string"
            calendar: 
              type: "array"
              items: 
                type: "object"
                properties: 
                  id: 
                    type: "number"
                  week: 
                    type: "number"
                  dayOfWeek: 
                    type: "number"
                  beginHour: 
                    type: "number"
                  endHour: 
                    type: "number"
                  status: 
                    type: "string"
                  featureId: 
                    type: "string"

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string

